sudo: required
dist: trusty
language: php

php:
  - 7.1
 
branches:
  only:
  - master #-> Staging Server
  - develop #-> DevServer

#Pre Execution
#testing dll
#build
before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - php artisan key:generate


#Main Execution
#Jalan
script:
  - ./vendor/bin/phpunit